//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string Bill_id { get; set; }
        public string Cus_id { get; set; }
        public string Emp_id { get; set; }
        public System.DateTime Create_date { get; set; }
        public Nullable<double> Total_Price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Bill_detail Bill_detail { get; set; }
    }
}
