//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_detail
    {
        public string Bill_id { get; set; }
        public string Product_id { get; set; }
        public string Discount_id { get; set; }
        public int Amount { get; set; }
        public double Total_price { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Bill Bill1 { get; set; }
        public virtual Discount_by_Rank Discount_by_Rank { get; set; }
        public virtual Discount_by_Rank Discount_by_Rank1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
