//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Bill_detail = new HashSet<Bill_detail>();
        }
    
        public string Product_id { get; set; }
        public string Product_type_id { get; set; }
        public string Product_name { get; set; }
        public double Sell_Price { get; set; }
        public System.DateTime Expired_day { get; set; }
        public int Quantity { get; set; }
        public bool On_discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_detail> Bill_detail { get; set; }
        public virtual Product_type Product_type { get; set; }
    }
}
